export enum UserRole {
  EMPLOYEE = 'EMPLOYEE',
  PROGRAM_ADMIN = 'PROGRAM_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INVITED = 'INVITED',
  DISABLED = 'DISABLED',
}

export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum TransactionType {
  ACCRUAL = 'ACCRUAL',
  ADJUSTMENT = 'ADJUSTMENT',
  RESERVE = 'RESERVE',
  WRITE_OFF = 'WRITE_OFF',
  RELEASE = 'RELEASE',
  EXPIRATION = 'EXPIRATION',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELED = 'CANCELED',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  HIDDEN = 'HIDDEN',
  ARCHIVED = 'ARCHIVED',
}

export enum OrderStatus {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  ASSEMBLED = 'ASSEMBLED',
  ISSUED = 'ISSUED',
  CANCELED = 'CANCELED',
}

export enum NotificationType {
  BALANCE_ACCRUAL = 'BALANCE_ACCRUAL',
  BALANCE_ADJUSTMENT = 'BALANCE_ADJUSTMENT',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_ASSEMBLED = 'ORDER_ASSEMBLED',
  ORDER_ISSUED = 'ORDER_ISSUED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  POINTS_EXPIRING = 'POINTS_EXPIRING',
  POINTS_EXPIRED = 'POINTS_EXPIRED',
  SYSTEM = 'SYSTEM',
}

export enum ImportJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
}

